id: P010599
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:15:53.929945
source_metadata:
  id: bdr:W1PD159439
  title: སྨྱུང་གནས་ཀྱི་རྣམ་གཞག
  author: ''
  volumes:
    0875bd252a5a46eabe65910fa016ee8e:
      image_group_id: I2PD19670
      title: ''
      volume_number: 1
      total_pages: 244
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
