id: IDD4DF4CE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:53:03+00:00'
last_modified: '2022-06-08T16:08:59.288165+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159439
  title: སྨྱུང་གནས་ཀྱི་རྣམ་གཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E221:
      image_group_id: I2PD19670
      title: ''
      total_pages: 244
      order: 1
      base_file: E221.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
